### ISSUE TITLE
chromedriver dependency broken in docker image v1.3

### ISSUE THREAD

**Issue by pranav7** [algolia/docsearch-scraper#456]
The chromedriver dependency in the latest docker image `v1.3` is broken, and errors out. Below is a stacktrace of the error.

```
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.9.125-linuxkit x86_64)
```

I did not run into the same issue when I used an older version: `v1.1.0`

**Comment by s-pace** [comment]
You are write, I will update it tomorrow. Sorry for the disappointment, you will enjoy the power of Algolia soon 🚀

**Comment by dbmalkovsky** [comment]
I just downloaded the latest docker image from https://hub.docker.com/r/algolia/docsearch-scraper which indicates that it is version 1.3.1. but when I run it it still reports <code>selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73</code>.

When I list out the docker images it indicates that the image is from 4 weeks ago:

<pre>
$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
algolia/docsearch-scraper   latest              5708d58e3240        4 weeks ago         1.59GB
</pre>

Did the image really get updated?

**Comment by s-pace** [comment]
Hi @dbmalkovsky 

Indeed the push failed at some point, fixed now. I have pushed it. Sorry for the inconvenience:

![image](https://user-images.githubusercontent.com/32097720/58418260-9af1f800-8087-11e9-931c-7991a851f440.png)

**Comment by dbmalkovsky** [comment]
Something is still wrong.  When I tried to update to "latest" nothing changed.  So I deleted the container and the image and fetched "latest" into a clean environment.  I then tried to run the "docker run" command and I'm still getting:
`selenium.common.exceptions.SessionNotCreatedException: Message: session not created: Chrome version must be between 70 and 73
  (Driver info: chromedriver=73.0.3683.68 (47787ec04b6e38e22703e856e101e840b65afe72),platform=Linux 4.9.125-linuxkit x86_64)`

**Comment by dbmalkovsky** [comment]
And when I list the images:

<pre>
$ docker images
REPOSITORY                  TAG                 IMAGE ID            CREATED             SIZE
algolia/docsearch-scraper   latest              5708d58e3240        4 weeks ago         1.59GB
</pre>

**Comment by dbmalkovsky** [comment]
@s-pace I just tried a clean install again with the same results.

**Comment by s-pace** [comment]
Can you download the image `algolia/docsearch-scraper:v1.3.1` . I have used it and it works fine.

**Comment by dbmalkovsky** [comment]
@s-pace Now that Chrome 75 and is being updated automatically (and Chrome 74 has a few nasty issues) can the chromedriver be updated again to the latest release?

The Latest stable release: [ChromeDriver 75.0.3770.8](https://chromedriver.storage.googleapis.com/index.html?path=75.0.3770.8/).  Thanks much.

**Comment by s-pace** [comment]
Thanks @dbmalkovsky It seems that chrome is not released yet. We will wait for a stable release #478

**Comment by dbmalkovsky** [comment]
@s-pace Are you sure about it not being release? My Chrome on both Windows and macOS is Version 75.0.3770.80 (Official Build), this [lists the updates for 75](https://developers.google.com/web/updates/2019/06/nic75) and I posted the link to the Chrome Driver 75.0.3770.7 previously.

**Comment by s-pace** [comment]
It seems that installing the stable version this way is not enough:

```
RUN curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
RUN echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list
RUN apt-get update -y && apt-get install -yq \
  google-chrome-stable \
  unzip
```
